export const VIEW_FOOT='VIEW_FOOT';
export const UPDATE_HOME='UPDATE_HOME';
export const UPDATE_DETAIL='UPDATE_DETAIL';
export const VIEW_LOADING='VIEW_LOADING';
export const UPDATE_GROUPS='UPDATE_GROUPS';
export const UPDATE_COUPON='UPDATE_COUPON';
export const UPDATE_MYORDER='UPDATE_MYORDER';
export const CHECK_USER='CHECK_USER';